### ISSUE TITLE
Naturalizations in Switzerland [Project]

### ISSUE THREAD

**Issue by simon-pinkmartini** [jsoma/data-studio-projects#14]
# Pitch

## Summary
A Turkish woman was recently denied citizenship in Switzerland, despite having spent all her life in the country (see story here: https://www.schweizer-illustrierte.ch/gesellschaft/thema/funda-yilmaz-aus-buchs-ag-einbuergerung-protokolle). This is an example of how arbitrarily the communes in Switzerland handle naturalization requests. My goal for this project is to gather data on granted citizenship and to make the differences between the communes visible.

### Data

The Federal Office of Statistics provides data on a commune-level going back from to 1991. We thus have 25 years of data to work with. The data contains the number of granted citizenship requests for each commune in Switzerland. I also have the population levels (Swiss and foreigners) by commune and will append other data to the analysis as needed (e.g. political preferences, average age, ...).

### Roadmap

The plan is to first create a couple of descriptive charts and tabes, isolating the places with high and low ratios of naturalizations (the tops and the flops). I am also going to look at the countrywide dynamics over the last 25 years, to get an idea on the general trend. I am also going to isolate some communes where the patterns have diverged from the national trend in a dramatic way. Insights from this analysis will inform me on the next steps.
In a second step, I will choose a meaningful statistic and create a choropleth map for the whole country (or: pick a couple of provinces and limit the map to these smalles levels - provinces typically have about 100 communes, the whole country has over 2000). I am not sure yet on what other information I will add to the map. Perhaps, just exporting the map to Ilustrator and add bits of information on some communes (the outliers) might be the best way to go ahead.

**Possible headline(s):** 
"What does it take to become Swiss?"
"Best and worst places to live if you want to become Swiss"

**Data set(s):** 
https://www.bfs.admin.ch/bfs/de/home/statistiken/bevoelkerung/migration-integration/erwerb-schweizer-buergerrecht-doppelbuerger.html
https://www.bfs.admin.ch/asset/de/su-d-01.02.04.08

**Code repository:** 
https://github.com/simon-pinkmartini/studio-projects/tree/master/code/Einbuergerungen
	
**Possible problems/fears/questions:** 
- Some of the communes in Switzerland are really small, with only 100 inhabitants or so. This means I will probably have a lot of noise in the data.
- I have data on the ACCEPTED request for citizenship but I don't have data for the DENIED requests. A crucial piece of information might thus be missing.
- There are several ways in which communes handle the process of granting citizenship. In some places, applicants just have to fill in a form and get questioned by a commission. In other places, the popular assembly actually gets to vote (yes!) on all citizenship requests. Also, there is some variation on the minimum number of years an applicant has to have lived in a commune. These processual differences might have a lot of explanatory power, but I don't have a categorized and complete set of data on it. Compiling this info might turn out to be very time-consuming.
- A further complication is that the geography of communes is not totally static over time. Once in a while, small communes decide to merge and form a bigger commune. I have to go into the data to see how I will deal with this.

## Work so far
I have downloaded the population and naturalization statistics and read them into pandas. I also got hold of a shapefile for the Swiss communities and linked the two together. Here's a simple (and obviously not very meaningful) plot of the naturalization rates (i.e. the number of citizenships granted divided by population levels.
![index](https://user-images.githubusercontent.com/28814395/28325858-f9ddab44-6bac-11e7-9b40-77b5dc1020d0.png)

## Checklist

This checklist must be completed before you submit your draft.

- [x] I have already spent time with my data set, opening it, exploring it, etc
- [x] I have created a "DIARY.md" file to save links and list all of the terrible, no good problems I come across
- [x] My issue issue has `[Project]` in the title
- [x] My issue links to my data set(s)
- [x] My issue links to my code repository
- [x] My issue explains what I'd like to explore in the data set
- [x] My issue includes images - either inspiration or what I've done so far
- [x] I have received two comments of peer feedback on my pitch issue

# Update
	
## Content
How I went from a map to a slideshow-like way of presenting the data.

## Data and story
After a few days of back-and-forth mailing with the Federal Office of Statistics, I finally got  well-structured dataset with naturalization numbers for all communes going back to 1981. (I spend about 2 whole days cleaning other crappy datasets they had sent me earlier). A number of different stories could be told with this data:
* How did the naturalization numbers change over time? When was the boom and what caused it?
* What's the matter with these ~40 communes that issued no citizenships at all over the last 35 years? (essentially, they are very remote places)
* Why is there so much yearly fluctuation over time in the data?
* Which communes have the highest and lowest ratio of naturalizations vs foreign population living there?
* ...
I finally settled on a story with the title "Where Swiss Are Made". This isn't an actual story, to be precise. It's more of an attempt to get the reader to explore the data and leave it up to him what kind of conclusions he wants to draw from it. The interactive now focuses on raw naturalization numbers (on a commune level) and on the ratio of naturalizations vs total population in a commune. I see this as an exercise in familiarizing myself with deeper html/css/javascript and exploring ways to mix storytelling and interactive presentation of data.
	
## Any changes in direction or topic?
I focused on design and user-experience. Instead of creating a single big map, I split the story up into three (can be extended to more) sections. Each section by itself is quite simple (in the sense that it contains just one chart which is very easy to read) - but the sections are also interactive, in the sense that the user can give some input and the graphs change depending on that. 

## Technical stuff
* I downloaded one of these sleek html/css templates that are designed for startups and freelancers who want to advertise themselves (https://tympanus.net/codrops/2015/01/27/freebie-boxify-one-page-website-template/). The nice thing is, it has slide-like navigation features built in and I don't need to do too much css myself.
* I used some javascript-based charts from chart.js (http://www.chartjs.org/docs/latest/). In principle, these charts should be easy to use and they render quite beautifully. In practice, the documentation is quite bad though. I spend a lot of time fiddling around with layout parameters.
* I used pandas / geopandas to produce json-like data structures that are loaded by the html / javascript and are used as inputs for the charts. 
	
## Problems/Questions
No problems or questions at this point, except that I might need some tips for another javascript charting library. Chart.js is ok once you know how to set all the parameters, but getting there is a painful task. Also, I feel like I need to go from "casual javascript user" to "advanced programmer" :-)

## Screenshots
<img width="1202" alt="screen shot 2017-07-24 at 11 36 50" src="https://user-images.githubusercontent.com/28814395/28531392-b93ffbf2-7064-11e7-9b6a-30ca027e18e3.png">
<img width="1222" alt="screen shot 2017-07-24 at 11 37 08" src="https://user-images.githubusercontent.com/28814395/28531403-c02b539e-7064-11e7-9ddd-05091e98c924.png">
<img width="1252" alt="screen shot 2017-07-24 at 11 37 20" src="https://user-images.githubusercontent.com/28814395/28531406-c1df43a8-7064-11e7-9250-49825bcdddc0.png">
<img width="1128" alt="screen shot 2017-07-24 at 11 37 37" src="https://user-images.githubusercontent.com/28814395/28531415-c520157e-7064-11e7-915f-816f0e0dc57e.png">

## Code
https://github.com/simon-pinkmartini/studio-projects/tree/master/code/Einbuergerungen

## Live Example
I finally managed to install a webserver on digital ocean and upload this project. You can check it out here: http://165.227.144.49/Einbuergerungen/web/swissmade.html make sure your browser window is big enough. And use Firefox or Chrome, DON'T USE SAFARI as it won't work there.
	
## Checklist
	
- [x] I have included my visuals
- [x] I have added writing about my topic
- [x] I have been updating my DIARY.md with details about my process
- [x] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository
- [ ] I have received two comments of peer feedback on my project update

# Final

## Details

**Headline:** How Swiss Are Made

**URL:** http://165.227.144.49/Einbuergerungen/web/swissmade.html

**Code:** https://github.com/simon-pinkmartini/studio-projects/tree/master/code/Einbuergerungen

**Comment by adaskalopoulou** [comment]
I would love to see this on a map. 
Can you compare the ratios with the number of foreigners living in the different places?

**Comment by demetriospogkas** [comment]
Good idea! Maybe you should build a hypothesis and try to test the data against it? Or you will just shoot for what you can come across from the data set?

**Comment by JulienAssouline** [comment]
This sounds interesting. I would also like to see this on a gender level. I would also be interested in seeing this on an application and acceptance level if you can find the data.

**Comment by playfairbot** [comment]
Greetings! This is the Playfair Bot, let's see what's been going on here.

Please post your **project draft!** It should be posted by **Friday**. More details available [here](/jsoma/data-studio-projects). If you posted one but I'm not seeing it, make sure you followed [the template](/jsoma/data-studio-projects/blob/master/UPDATE_TEMPLATE.md).

**Comment by Ediegram** [comment]
This is very nice! At first I didn't choose a place because I don't know the country well and then all the charts were empty. This text should alert people to the dropdown and users should be allowed to progress to the next stage without choosing a town.


<img width="390" alt="screen shot 2017-08-01 at 8 26 34 pm" src="https://user-images.githubusercontent.com/18584853/28852543-eac5b0a6-76f7-11e7-8194-bb83ebc1fc0b.png">

I am not a fan of running charts over images but if you want to go that route you need to take great care making sure everything is legible. The first two are ok but the maps are not clear over that image and the highlight colors are too subtle. One thing you can do is run the black and white images but continue with that red accent from the introduction for charts and map.
