### ISSUE TITLE
Tracking forest fires in Europe

### ISSUE THREAD

**Issue by castorsia** [jsoma/data-studio-projects#174]
Please complete all of the following sections, or the ghost of Joseph Pulitzer will spookily dance around your issue! A completed version of this template can be found at https://github.com/jsoma/data-studio-projects/issues/1

# Pitch

My intent: to track (forest) fires in the European Union and in Greece, specifically. For that, I use data from the European Forest Fire Information System [EFFIS](http://effis.jrc.ec.europa.eu/). I want to find out: the countries most affected, recent trends for the Mediterranean, compare severity through burned areas.

## Details

**Possible headline(s): Fire season is already here: A look at the data

**Data set(s): At the moment, 3 datasets are used, featuring: 1) The number of fires for 2017, for every country
                                                                           2) The yearly number of fires per country since 1980
                                                                           3) The total burned areas per country per year

**Code repository:** (https://github.com/castorsia/data-studio/commit/3bf4df5063addd8312e96001d7ce277bd362de2b)
	
**Possible problems/fears/questions:** 

I tried using a personal style that I have created... With tragic results in the x axis.

## Work so far

Cleaned up my datasets, dropped non-EU countries, investigated the huge amount of Ukraine and Russia fires, and then started a lacklustre plotting.. 

10 most impacted countries for 2017

![download](https://user-images.githubusercontent.com/39416165/42800464-fd12bfc6-8969-11e8-96a0-db0081d70fd7.png)

## Checklist

This checklist must be completed before you submit your draft.

- [X ] I have already spent time with my data set, opening it, exploring it, etc
- [ ] I have created a "DIARY.md" file to save links and list all of the terrible, no good problems I come across
- [X ] My issue links to my data set(s)
- [ X] My issue links to my code repository
- [ X] My issue explains what I'd like to explore in the data set
- [ X] My issue includes images - either inspiration or what I've done so far

**Comment by jsoma** [comment]
* I'm not sure which of your questions the graphic is answering! Title + subhead please.
* Oh boy, Portugal. Maybe start with that graphic, then another graphic that's specifically about Portugal how it ended up like that?
* I'd go with a font that's a little wider, less condensed. It makes it tough to read when the text is pushed together, y'know?
* Don't need those tick marks, since you have bars and labels. `ax.tick_params(axis='y', left=False)` I think?

**Comment by castorsia** [comment]
# Update
	
## Your project content: images/words/etc
	
![2018-07-20 00_49_25-project_2_v_0-copy1](https://user-images.githubusercontent.com/39416165/42984212-7618e462-8bb9-11e8-89e2-e01e75550df4.png)

Something terrible must have happened to Portugal in 2017. It was this: (https://www.bbc.com/news/world-europe-41634125) 

![elaaaa_1](https://user-images.githubusercontent.com/39416165/42984339-15a8144e-8bba-11e8-8a38-27aafcf6fa03.png)


## Any changes in direction or topic?

-Focused on Portugal and the fires that ripped the country apart. 
-Added heading and subhead
-Changed the colours
-Different font
-dropped the tick marks
	
## Problems/Questions
  
Can not get a specific column and save it as a new dataframe (say, Portugal, featuring years and burnt areas). I get an out of index error. Have to go around it... Get two dfs and concat them.
-Dead space in the second line graph. I want to loose it!

##
Code: (https://github.com/castorsia/data-studio/commit/e10a0a663fc538d410e492af4373e793afa4a68a)

## Checklist
	
- [X ] I have included my visuals
- [ X] I have filled out the sections above
- [ ] I have been updating my DIARY.md with details about my process
- [ X] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository

**Comment by playfairbot** [comment]
Greetings! I'm a little robot, checking in on your project.

You need some feedback, let me summon @cfelke, @dz2383, @vpenney for you

**Comment by vpenney** [comment]
You can actually omit the parenthesis when you list the number of hectares that burned in your bar chart--I initially read that as "ha" as in "haha," but forest fires aren't very funny. Alternatively, since you define the measure in the title, you can omit "ha" in your bars entirely, or use a simple legend like you use in your line graph. 

Your line graph could be an interesting opportunity to use some of that blank space in the graph to explain the peaks and troughs in the graph (like what Bui talked about). That would probably come later, once you get everything into Illustrator, but it would be interesting to know if those spikes follow a drought cycle or if there were big fires in those peak years that drove up the number of burned acres.

**Comment by cfelke** [comment]
Wow, what's going on in Portugal? I really like your second graph. It would be great to have some annotations in your line graph, especially for 2003(?) and 2005 (are the peaks related to the same reason? If so, you could make one text field with two arrows pointing at both years) and definitely for 2017.
Regarding the empty space you're not satisfied with, you can fill it up (Angela did this in her first project e.g. https://github.com/jsoma/data-studio-projects/issues/138)

Regarding the first graph, if you're already displaying the 5 countries with the biggest losses of forests I don't think you need to put this in your title as well. I'd ditch the country abbreviations on your y axis and choose a brighter colour for your values, maybe orange (= fire, wooh!), in fact anything but black. I'm not sure if you need to put the ha next to your values, if you're already labeled your x-axis with ha and it's in the title too. Maybe ditch one of those. Moreover, some x grid lines for orientation might be helpful, give it a try.

**Comment by dz2383** [comment]
I love the topic! For improvements: could you get rid of the black lines in two graphs( bottom and right side)? And add grid at the background for the line graph? Because now it's hard to read the number.

**Comment by castorsia** [comment]
# Update
	
## Your project content: images/words/etc
	
I struggled to find a good angle in approaching my data, because, for example, forest hectares burnt, is just a number. How it can be translated to patterns? Are 29.000 hectares of forest burned, not important, compared with bigger fires? So, I took a jab in providing some more graphs with info. STILL TO DO: Context for Portugal and Greece and Iberian wildfire spikes.

![2018-07-27 01_42_06-project_2_rev_2](https://user-images.githubusercontent.com/39416165/43304363-d65a8e74-9141-11e8-99b7-84c14d6361e2.png)
![2018-07-27 01_57_33-project_2_rev_2](https://user-images.githubusercontent.com/39416165/43304366-da68f80c-9141-11e8-8421-56b57d96bcde.png)
![2018-07-27 01_58_08-project_2_rev_2](https://user-images.githubusercontent.com/39416165/43304370-dda64ec0-9141-11e8-9225-fc4abd6c58a1.png)
![2018-07-27 01_58_30-project_2_rev_2](https://user-images.githubusercontent.com/39416165/43304372-df9d29c4-9141-11e8-949b-44f6e5bb8174.png)

  
## Any changes in direction or topic?
  
There's a real need to look into country-specific conflagrations-and their reasons.

## Problems/Questions
  
-I must find more creative ways to communicate the data. I have the same graphs over and over again.
-Imperative to find a way to visualise the scale of the forest fire problem.
-I will compare Greek fire service data with the European Union.

## Checklist
	
- [ X] I have included my visuals
- [ X] I have filled out the sections above
- [ ] I have been updating my DIARY.md with details about my process
- [ X] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository

**Comment by mattrehbein** [comment]
Personally, I think simply showing which countries have experienced/are experiencing a greater frequency in fires is interesting. That information certainly begs the question of why for the individual countries that have seen great increases, but getting into why may be a lot for the scope of this project. Are you looking for drought data or something similar if you're trying to get to the cause?

This may be a silly question but just to be clear about your terminology: Your focus is forest fires -- so we're only looking at fires in wooded natural areas? Is this the same as wildfires? Do they threaten inhabited areas, destroy any buildings or cause fatalities?

Practical, nit-picky things about the graphs that you're probably already working to fix:

- need commas in big numbers
-I don't get anything out of having the bracketed abbreviation of each country in the y axis -- is there a reason for it?
-in your first graph, exact values per bar are too hard to read, and I'd lose the scale at the bottom if you're already giving the exact figures
-legend and subtitle in the first Portugal-specific graph both say same thing.
-legend in the Greece fires chart is a bit confusing: each bar is hectares burnt, right? Not 'fires'

**Comment by maxarvid** [comment]
Really interesting project, and something that will only become more important as Europe experiences ever increasing heat waves. 

Some quick notes:
- Same on the abbreviations for EU countries, I think they are superfluous and should be dropped.
- Same on adding some commas in the big numbers-
- On the final graph, the x-axis is very busy. I think x-ticks as on the two previous graphs (i.e. every five years).
- Final graph again, drop the legend box.
- Final graph again, suggestion for the text / annotation: Explore why there were so few fires in 2003, was it a particularly rainy summer?
- I think I understand the reasoning for lowering the x-axis in graph 2 and 3, it's just that they've been lowered by different amounts. I suggest making them the same.

**Comment by julialedur** [comment]
Cool project! As improvements, I would: 

- standardize the style of all graphs. In the first one, you have a different color scheme and font size 
- In your first graph, sort the bars in a descending order. Also get rid of the country abbreviations on the y-axis. Finally, I think it would be more effective and easier to read if you had the exact values of the bars as annotations instead of numbers inside the bars. 
- In the second graph, you can get rid of the legend, since you already specified that the line refers to hectares on the subtitle.
- I agree that in your last graph the x-axis is very busy. You might want to add a tick label every five years. You can also delete the legend "year".
- add commas to the tick label values.
- It would be interesting to know why there were so many fires in Portugal in 2003. Maybe you could add annotations to that graph with short explanations.

I'm looking forward to seeing your next version! :)

**Comment by castorsia** [comment]
# Update
	
## Your project content: images/words/etc

The Iberian peninsula is reportedly about to break the European heat wave record, with temperatures expected to touch 50 degrees Celsius, while thousands have been mobilised to avert fires. Greece was ravaged by wildfires with the highest death toll in its history, more than 90 people. So, what worst time for an update.... Forest fires, to clear things up RE terminology, are fires that begin in forests. They expand to other types of terrains, in crops, houses, suburbs, villages etc. So, they (can) cause causalities.  

Initially, I made the first graph easier to the eye.	
![1_graph-bar-5-largest_areas_burnt](https://user-images.githubusercontent.com/39416165/43560329-f04e573c-95df-11e8-9c62-6f83bad0a314.png)

And provided a bit of context for what is going on with Portugal.

![2_graph-line-portugal-burnt-hectares-per-year](https://user-images.githubusercontent.com/39416165/43560330-f219bc00-95df-11e8-8aa6-91f5f46d30bc.png)

The patterns are quite strong, as we can see.

![3_graph-line-top-5-fires-per-year](https://user-images.githubusercontent.com/39416165/43560332-f44220b2-95df-11e8-8b63-9aa01ec635f8.png)

A closer look at Greece. 

![4_graph-bar-greece-burnt-hectares-per-year](https://user-images.githubusercontent.com/39416165/43560339-fa0c9cca-95df-11e8-966a-f3c762446835.png)

Since we are speaking about Greece, I encountered the following problem: each summer the country is going up in flames, but due to its considerably smaller size than other countries in the graphs, the scale of the issue is not easy yo convey. 50.000 burnt hectares for Greece is huge, but for Spain, which is many times bigger than Greece... It is not.

 So, I grabbed historic forestry data from the EU about the total forest cover of each country in 1990, summed up the burnt areas since 1990 until last year, and calculated what percentage of the 1990 forests, are the burnt areas.

I used pywaffle, which I don't really know how to use... Evidently. But it is a place to start.
 
![spain_1990](https://user-images.githubusercontent.com/39416165/43561060-453adc90-95e3-11e8-825c-8f043f2139bd.png)
![cypr_1990](https://user-images.githubusercontent.com/39416165/43561086-63d4f348-95e3-11e8-94f7-d82f9e3f0eac.png)
![italy_1990](https://user-images.githubusercontent.com/39416165/43561091-691f215c-95e3-11e8-8bfe-4b4447171df2.png)
![greece_1990](https://user-images.githubusercontent.com/39416165/43561093-6cdb7f02-95e3-11e8-8b9d-6dc8e5c0a126.png)
![port_1990](https://user-images.githubusercontent.com/39416165/43561099-7023f3b0-95e3-11e8-8c03-1ddb260a7919.png)


## Any changes in direction or topic?

I had to move away from absolute values to relative (percentages).

##Code

(https://github.com/castorsia/data-studio/blob/master/code/project_2/Draft_1/Project_2.ipynb)
	
## Problems/Questions

-I need to find a way to better visualise the percentage of lost forests. Ideas, and most importantly, ways that it can be done?
- I have precipitation and temperature data for the Iberian peninsula, I need to incorporate them in my graphs.
-   Maybe using the data of the Greek fire service? Some interesting things to be found there, but not sure it would really add something new. 

Delete this line and complain about any problems you've run into (solved or unsolved)

Tables, tables, tables! CSVs in different orientations, indexes, I had to manually change things.

## Checklist
	
- [ X] I have included my visuals
- [ X] I have filled out the sections above
- [ ] I have been updating my DIARY.md with details about my process
- [X ] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository
