### ISSUE TITLE
03-Broadway Ticket Pricing

### ISSUE THREAD

**Issue by kellykiki** [jsoma/data-studio-projects#209]
Please complete all of the following sections, or the ghost of Joseph Pulitzer will spookily dance around your issue! A completed version of this template can be found at https://github.com/jsoma/data-studio-projects/issues/1

# Pitch

## Summary
As a theater junkie, I usually watch approximately 20 plays per year in Athens. In New York, one or two Broadway musicals will probably be my cultural investment for the summer. At the moment and for the time given, I cannot take into account the productions cost and provide you with the full story on "Broadway economics", as [Economist](https://www.economist.com/graphic-detail/2016/06/16/breaking-down-broadway) did; but I can have a look at the "easy" part of the story:  Broadway tickets pricing. 

With this project, I am working on recent Broadway grosses (last weeks) and, if possible, I aim to analyze some data regarding Broadway 2017-2018 season, going back upto November 2017. 

- Major source: [Broadway World](https://www.broadwayworld.com/grosses.cfm)

Possible additional sources, if needed:
- [Broadway League](https://www.broadwayleague.com/research/grosses-broadway-nyc/)
- [Internet Broadway Database](https://www.ibdb.com/grosses-all/1)

## Details

**Possible headline(s):** A glance at Broadway box office

**Data set(s):** https://www.broadwayworld.com/grosses.cfm

**Code repository:** https://github.com/kellykiki/data-studio/tree/master/code/03-broadway
	
**Possible problems/fears/questions:** 
- After scraping, I have a huge dataframe. I probably cannot make it to go as far as I wish in terms of analysis in the time given. For further details, please see "Work so far/Part 2".
- How can I convert upper case to lower case at once in my dataframe?

## Work so far
I have worked in two parts.
### Part 1: Weekly analysis
- I have scraped grosses for the last week (July 16 - July 22, compared to July 9 - July 15). See [here](https://www.broadwayworld.com/grosses.cfm).
- I have cleaned data and transformed the original dataframe, using regex
- I have done some analysis and I have produced some draft graphs that you can find below

### Part 2: Breaking down the 2017-2018 season
- I have scraped grosses for past weeks going back to November 2017, aiming to do some analysis for the season. See [here](https://www.broadwayworld.com/grosses.cfm)
- I have cleaned data and transformed the original dataframe, which remains huge: Because grosses are given on a weekly level each time compared to the previous week for each show, aggregating data and narrow down the original dataframe to different ones will not be easy. 

### Graphs for Part 1 - Weekly level (July 16 - July 22)

Graph 1 - Average ticket by show
![avg_ticket](https://user-images.githubusercontent.com/39416357/43117427-bffb0fb4-8eda-11e8-883e-610a3f23e3f5.PNG)

Graph 2 - Top ticket by show
![top_ticket](https://user-images.githubusercontent.com/39416357/43117460-dde3e884-8eda-11e8-9439-b80c904d8614.PNG)

Graph 3 - Weekly grosses compared to the previous week
![weekly_grosses](https://user-images.githubusercontent.com/39416357/43117474-f28d2066-8eda-11e8-8331-7e66df2e0fc6.PNG)

Graph 4 - Seats Available vs Seats Sold by show
![seats_sold_vs_available](https://user-images.githubusercontent.com/39416357/43117478-fdd47e60-8eda-11e8-9354-d97911b64bb7.PNG)

Graph 5 - Difference in grosses compared to previous week 
(a lot of work to be done here)
![diff_sold](https://user-images.githubusercontent.com/39416357/43117572-7dc1e1e4-8edb-11e8-9da1-f3c971701aca.PNG)

## Checklist

This checklist must be completed before you submit your draft.

- [X] I have already spent time with my data set, opening it, exploring it, etc
- [ ] I have created a "DIARY.md" file to save links and list all of the terrible, no good problems I come across
- [X] My issue links to my data set(s)
- [X] My issue links to my code repository
- [X] My issue explains what I'd like to explore in the data set
- [X] My issue includes images - either inspiration or what I've done so far

**Comment by kellykiki** [comment]
# Update
	
## Your project content: 

#### Graph 1
### Average ticket price by show
#### How much tickets cost on average, if you want to watch bestseller shows
![avg_ticket](https://user-images.githubusercontent.com/39416357/43290791-2e02e058-90fd-11e8-9501-78986f1f1317.PNG)

#### Graph 2
### Top-ticket by show
#### Yes, some people booked a ticket for more than 800$
![top_ticket](https://user-images.githubusercontent.com/39416357/43290988-e0859c8e-90fd-11e8-89b0-ac16aabe1948.PNG)

#### Graph 3
### Seats Sold vs Seats Available 
#### "The Lion King" and "Harry Potter" were sold out last week
![seats_sold_vs_available](https://user-images.githubusercontent.com/39416357/43291160-83acbdac-90fe-11e8-856a-5c3eb743b0b7.PNG)

#### Graph 4
### Box office results
#### Last week grosses vs previous week grosses
![current_vs_previous_week](https://user-images.githubusercontent.com/39416357/43291297-ec7c8876-90fe-11e8-854e-ffd856613750.PNG)

#### Graph 5
### Difference in box office results compared to the previous week
#### Winners and losers by bestseller
![difference_grosses](https://user-images.githubusercontent.com/39416357/43291486-98db79ba-90ff-11e8-8ec8-9e12521a3ecc.PNG)

#### Graph 6
### Percentage difference regarding seats sold compared to the previous week 
#### The "Bronx Tale" gets more fans two weeks before its closing
![diff_sold_seats_pct](https://user-images.githubusercontent.com/39416357/43291604-158d5ea6-9100-11e8-8110-90b50bac1b59.PNG)
  
## Any changes in direction or topic? 
Not really
	
## Problems/Questions
I have problems regarding the second part of my project (seasonal variations). Scraping the page and getting all data available is really hard; keep trying.
	
## Checklist
	
- [X] I have included my visuals
- [X] I have filled out the sections above
- [ ] I have been updating my DIARY.md with details about my process
- [X] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository

**Comment by sarahslo** [comment]
i would try to make these charts with muted colors. the red and the black and both so strong they fight each other and we only look at the shape and not the data. yellow is a very hard color to work.

your job here is to make the visualization clear, so less is more. pick one strong color so we know where to put our eyes, and take out color otherwise. you are clearly enjoying playing with the contrast and that's great. i'd play with separating the information out and toning back the rest.

**Comment by Palarisk** [comment]
Hi, great work. I really liked the information I got fromgraphs 1-3. My only comment is for the graph 3: it was a bit hard to understand first. I first understood it meant that approx half of the tickets were not sold (I understood that available meant unsold tickets). Maybe you could do a stacked bar chart, where in the end of the bar would be the unsold tickets?

**Comment by SiruiZhu** [comment]
This topic is amazing!! I love it!

- I understand the first two charts, but the third one"Seats Sold vs Seats Available", why there are some one seat sold is more than seats available? just curious.

- Your color scheme met broadway theme, however it's hard to me to read the data and the texts, maybe try a different color scheme?

**Comment by kellykiki** [comment]
# Update - Revision 2
	
## Content
#### Part 1 - weekly (data are updated and refer to the week ended on July 29)	

#### Graph 1
### Average ticket price by show
#### How much tickets cost on average, if you want to watch bestseller shows
![avg_ticket](https://user-images.githubusercontent.com/39416357/43563978-86944a46-95f2-11e8-9eee-681a9ca4b2a2.PNG)

#### Graph 2
### Top-ticket by show
#### Yes, some people booked a ticket for more than 800$
![top_ticket-01](https://user-images.githubusercontent.com/39416357/43564014-abba3df8-95f2-11e8-8716-7c3b1e64ec3c.png)

#### Graph 3
### Seats Sold vs Seats Available
#### "The Lion King" was sold-out
![seats_sold_available-01](https://user-images.githubusercontent.com/39416357/43564040-d70d3d7a-95f2-11e8-9ccd-0db3084a033a.png)

#### Graph 4
### Box office results
#### Last week grosses vs previous week grosses
![box_office-01](https://user-images.githubusercontent.com/39416357/43564086-13c8c806-95f3-11e8-807e-f2a512107554.png)

#### Graph 5
### Difference in box office results compared to the previous week
#### Winners and losers by bestseller
![difference-01](https://user-images.githubusercontent.com/39416357/43564107-3de9fd08-95f3-11e8-8ed9-9876ad59a018.png)

#### Graph 6
### Percentage difference regarding seats sold compared to the previous week
![diff_sold_weekly-01](https://user-images.githubusercontent.com/39416357/43564145-67684540-95f3-11e8-9077-52d34dffc3cc.png)

#### Part 2 - Seasonal (Nov 2017 - June 2018)

#### Graph 7
### Tickets sold by month in Broadway 
![months-01](https://user-images.githubusercontent.com/39416357/43564232-d3e80728-95f3-11e8-8b8a-8c1101c1b844.png)

#### Graph 8 
### Average number of tickets sold by top-seller
![avg_seats_sold_season_top15](https://user-images.githubusercontent.com/39416357/43564297-286a8a78-95f4-11e8-8403-a5fcd03e48e1.png)

#### Graph 9 
### Average gross by show for the season
![gross_mean_season](https://user-images.githubusercontent.com/39416357/43564325-48cb93d4-95f4-11e8-8ae2-4e88f7036947.png)

#### Graph 10
### Total gross by top-theater for the season
![theater_grosses-01](https://user-images.githubusercontent.com/39416357/43564359-691e018a-95f4-11e8-84d6-5f5ad8ee4fda.png)
(Numbers to be added in bars soon)
  
## Any changes in direction or topic?
Nope
	
## Problems/Questions
Didn't have time needed to do some more things I wish.
	
## Checklist
	
- [X] I have included my visuals
- [X] I have filled out the sections above
- [ ] I have been updating my DIARY.md with details about my process
- [X] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository

**Comment by kellykiki** [comment]
# Final

## Project visuals/text

## Part 1 - Weekly 

### Average ticket price by bestseller show
#### 382$ is the difference between Springsteen on Broadway and The Band'S Visit average prices
![avg_ticket_weekly](https://user-images.githubusercontent.com/39416357/43689693-5f26e0fe-98cc-11e8-9fdb-8d9f88c438ba.png)

### Top-ticket by show
#### It isn't the first time that some people booked tickets for more than 800$
![top_ticket_weekly-01](https://user-images.githubusercontent.com/39416357/43689708-7f69f248-98cc-11e8-83e4-632dbcbd2b7f.png)

### Seats sold vs Seats available
#### Amongst shows with the largest seating capacity, The Lion King and Harry Potter were sold out
![seats_sold_available_new-01](https://user-images.githubusercontent.com/39416357/43689732-a66b380c-98cc-11e8-96d7-a0f008b6be79.png)

### Box office results
#### Last week grosses vs Previous week grosses
![box_office-01-weekly](https://user-images.githubusercontent.com/39416357/43689758-10763558-98cd-11e8-9d32-aef929ca63f5.png)

### Difference in box office results compared to the previous week
#### The Book of Mormon, Carousel, Aladdin and Come from Away were last week losers
![difference-01-weekly](https://user-images.githubusercontent.com/39416357/43689789-6eb2b650-98cd-11e8-8166-e2411158c554.png)

### Percentage difference about seats sold compared to the previous week
#### The Waitress increases tickets sold by 10%, while Carousel decreases sales by nearly 4%
![diff_sold_weekly-01](https://user-images.githubusercontent.com/39416357/43689764-24cfe242-98cd-11e8-9af4-607c742cf29a.png)

## Part 2 - Seasonal

### Tickets sold by month in Broadway
#### April is the month with the highest attendance, if we don't take into account the Christmas time
![months-01-01](https://user-images.githubusercontent.com/39416357/43689798-8f41d356-98cd-11e8-935f-4403a4517b15.png)

### Weekly average proportion of seats sold on theaters seating capacity
#### The Book of Mormon was constantly sold out during the season 2017-2018
![avg_pct_sold_season-01](https://user-images.githubusercontent.com/39416357/43689805-a5430e18-98cd-11e8-86a2-dbfec4cd7173.png)

### Weekly average gross by show for the season
#### Hamilton grossed nearly 3.1M $ per week
![gross_mean_season_new-01](https://user-images.githubusercontent.com/39416357/43689813-c1777e48-98cd-11e8-8944-bd41b08d484b.png)

### Total gross by top-theater for the season
#### Hamilton magic made Richard Rodgers theater the big winner
![theater_grosses-01](https://user-images.githubusercontent.com/39416357/43689827-e839e9da-98cd-11e8-8dae-789864205343.png)


## Details

**Headline:** 
#### BROADWAY BOX OFFICE
### Average ticket to Springsteen's one man show hit 509$

**Published website version:** https://kellykiki.github.io/broadway/

**Code repository:** https://github.com/kellykiki/data-studio/tree/master/code/03-broadway

**Final data set(s):** https://www.broadwayworld.com/grosses.cfm

## What did you find to be the most difficult part of this project? 
Scraping seasonal data

## Are you satisfied with what you produced? Is there anything you would like to change or improve? 
I had more ideas regarding seasonal data analysis that I didn't have the time to work on. I am bored of the bar charts :(  I find that they help information being visualized clearly, though 

## Checklist

- [X] I have included my visuals
- [X] I have posted my project to my project website
- [ ] I have been updating my DIARY.md with details about my process
- [X] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository
