### ISSUE TITLE
[PROJECT] How much of Hamburg is dedicated to cars?

### ISSUE THREAD

**Issue by jlstro** [jsoma/data-studio-projects#253]
# Pitch

## Summary

The project will try to answer the question given in the title: How much of the surface area of my hometown Hamburg is dedicated to cars? The basic idea is to come up with a percentage and/or total of all the surface area of the city that is constructed for automotive transportation, e.g. streets & car parking areas, gas stations, highways, bridges... If possible, I'll try calculate the corresponding figure for bikes and trains/metro as well as a comparison. If all goes well, I will also compare different areas of the city: Rich/poor neighbourhoods, industrial/resident, touristy/non-touristy, etc.

I took inspiration from [this](https://oldurbanist.blogspot.com/2011/12/we-are-25-looking-at-street-area.html) and [this](http://oldurbanist.blogspot.com/2011/06/density-on-ground-cities-and-building.html) article.
## Details

**Possible headline(s):** 
_N percent of Hamburg's surface is dedicated to cars, only x to bikes
Every car uses up N square meter in Hamburg
Cars use up a lot of space: Here's how much exactly_
**Data set(s):** 
I will work with data from OpenStreetmap. I'll have to figure out how exactly I measure the area.
**Code repository:** 
will provide link later
**Possible problems/fears/questions:** 
I think the biggest problem is to measure the area of streets correctly, so identify which non-street parts of a city are dedicated to cars
## Work so far
Nothing to show, sorry
## Checklist

This checklist must be completed before you submit your draft.

- [ ] I have already spent time with my data set, opening it, exploring it, etc
- [ ] I have created a "DIARY.md" file to save links and list all of the terrible, no good problems I come across
- [ ] My issue links to my data set(s)
- [ ] My issue links to my code repository
- [x] My issue explains what I'd like to explore in the data set
- [ ] My issue includes images - either inspiration or what I've done so far

**Comment by sarahslo** [comment]
hmm. interesting. can you tell us, how much is living space and how much is park space too?

**Comment by jlstro** [comment]
# Update
	
## Your project content: images/words/etc
I loaded Hamburg's street grid into qgis, so here's a screenshot
![grafik](https://user-images.githubusercontent.com/3785873/44098956-82b5eecc-9faf-11e8-8f8f-bf6ad0e8971c.png)
This is not actually part of the project but it looks cool. So far, everything happened inside a notebook. There are no cool graphics yet.
  
## Any changes in direction or topic?
I think I will compare the Hamburg districts with each other in the end, so the individual data sets are a bit smaller / easier to handle. There are 30.000 plus street segments in Hamburg, I thought it was much less.
	
## Problems/Questions
  
Despite all prejudice, German streets are not all the same size/width. That makes it a bit complicated to figure out the actual area - so far, all I have is length.
	
## Checklist
	
- [ ] I have included my visuals
- [ ] I have filled out the sections above
- [ ] I have been updating my DIARY.md with details about my process
- [ ] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository

**Comment by jlstro** [comment]
@sarahslo Yes, I will try to divide the remaining (non-car) areas into resident, recreation, etc. That should be fairly easy with the data I have I hope.

**Comment by jessimckenzi** [comment]
Really interesting! Are you planning on doing a map, or something that hacks up the info and makes it into something else, like an area chart of some kind? (Like a waffle chart, but you could make the space dedicated to cars pictures of cars, dedicated to bikes pictures of bikes, dedicated biz pic of a shop, dedicated residential pic of a house, etc.) Lots of possibilities! Excited to see what comes next.

**Comment by jlstro** [comment]
# ~ 1/15 of Hamburg is road/parking surface!
![grafik](https://user-images.githubusercontent.com/3785873/44289267-70922500-a241-11e8-8e58-d07514317075.png)
Unfortunately, I won't be able to finish this project in due time. I will come back after Lede and make it nice. Here's a map of what I did so far: red is car-stuff (parking, roads), light orange is public transportation. Light grey are buildings, green / blue is parks and water and dark grey is "other" - mostly industrial areas and some agriculture. _The streets width is not to scale!_

Here's what I did so far:

### The project diary
=================
* Download Hamburg OSM data from [here](http://download.geofabrik.de/europe/germany/hamburg.html). Could've done it in QGIS with the QuickOSM plugin but the performance really sucks
* Download district boundaries of Hamburg from [here](http://suche.transparenz.hamburg.de/dataset/alkis-verwaltungsgrenzen-hamburg)
* install osmctools with apt
* convert file downloaded in step 1 to .osm and filter with the following options to only keep streets:
*osmfilter hamburg-latest.osm --keep="highway=residential =primary =secondary =tertiary =unclassified" --drop="public_transport=stop_position public_transport=platform public_transport man_made boundary leisure amenity highway=traffic_signals =motorway_junction =bus_stop railway building entrance=yes barrier=gate barrier shop" > temp.osm*
* creat geojson from osm file for easier use in python with [this cli tool](https://tyrasd.github.io/osmtogeojson/)
* load geojson into jupyter notebook
* clean data, put into df
* read about haversine formula for hours, understand nothing, get confused, read more
* eventually calculate length in meter from lat/long points
* measure 4 randomly chosen streets of each highway type (*residential, secondary, primary,* etc...) and take mean of width for each type
* multiply length by width and number of lanes to get street area - I double checked with [this document](https://www.hamburg.de/bwvi/restra/), that says that inner city street lanes are around 3,8m - very roughly corresponds with my measurements
* calculate area of each district in Hamburg. I did this in QGIS with the field calculator and exported it to csv and load it into my notebook.
* Alright - around 5 per cent of all surface area are streets!
* add district to street info. I should've done this before: Use QGIS to find out which street is in which disctrict, clean up a bit (some are in multiple districts), export info to csv, join on unique street id with existing df
* check for other object types with *osmfilter*:
*osmfilter hamburg-latest.osm --keep="building" --drop="building=parking" > all_buildings.osm && osmfilter hamburg-latest.osm --keep="natural leisure landuse=grass" --drop="natural=water" > parks_recreation.osm && osmfilter hamburg-latest.osm --keep="natural=water" > water_areas.osm && osmfilter hamburg-latest.osm --keep="amenity=parking =parking_space =fuel =car_sharing =taxi building=parking" > parking_buildings.osm && osmfilter hamburg-latest.osm --keep="amenity=bus_station public_transport railway" --drop="tunnel=yes" > public_transport.osm*
* import it all into the map

### to-do
* spatial-join info of each district to all other objects (to distinguish which district an object is in) and calculate total/relative area for each type of surface use for each district
* make it all look nice
* ...profit?
